### PR TITLE
build(deps): bump `rclone` to `1.61.1`

### PR DESCRIPTION
**Pull request by davralin**
Upgrade rclone to latest version.

### CODE REVIEW

**Comment by jamesmyatt** [comment]
I was about to ask for this. I need v1.60 for SMB remotes.

**Review by jcwillox — APPROVED** [review]
Thanks, yeah I need a better way to keep this addon up-to-date with rclone

**Comment by davralin** [comment]
> Thanks, yeah I need a better way to keep this addon up-to-date with rclone

Perhaps dependabot or renovate can help with that?

I have to admit, I have no idea how this plugin-system really works, so I just hoped changing the numbers was enough! If I can do that, I'll bet some random bot online can do the same!

**Comment by jamesmyatt** [comment]
Thanks @jcwillox and @davralin .

@jcwillox Are you planning to release this version soon? (just in case you've forgotten 😉 )

**Comment by jcwillox** [comment]
Yep, I'll release it in like the next hour when I get back to my pc, I was testing out this other feature to see if it was something simple I could include in this release, but I'll do that in a future release.

**Comment by jamesmyatt** [comment]
No problem. Like I said, I just wanted to be sure you hadn't forgotten. Don't let me pressure you into rushing.

**Comment by jcwillox** [comment]
It's all good I was gonna publish it tonight one way or another https://github.com/jcwillox/hassio-rclone-backup/releases/tag/3.0.1. It's good you checked though, I've had many a PR merged and then waited forever to actually get a release with the feature 😄

**Comment by s-e-t-h** [comment]
> Thanks, yeah I need a better way to keep this addon up-to-date with rclone

Hi JC, is this still up-to-date and did you find a way to keep it up-to-date?
Thanks

**Pull request merged**
